### PR TITLE
Updated to newest Android SDK Tools version 25.1.7

### PR DESCRIPTION
**Pull request by rzimmer**
Although not reflected on the official [SDK Tools Release Notes](https://developer.android.com/studio/releases/sdk-tools.html), version 25.1.7 of the SDK Tools is out.

Changes may not be so exciting, but hopefully a new version of the Dockerfile will make re-build the container, pulling in Android Support Libraries in version 23.4.0, which have been released recently (see [release notes](https://developer.android.com/topic/libraries/support-library/revisions.html). Currently, builds are failing when using the newest version as dependency, because they are not in the Docker container yet.

Thanks a lot for your really great Gitlab CI runner, lovin' it!

### CODE REVIEW

**Comment by jangrewe** [comment]
Thanks for the MR, the new image should be available shortly!

This is the content of the new image, unfortunately it still uses Android Support Library 23.2.1, even though it notes that the version is already obsolete. I'll have to investigate why this is happening...

```
- Android SDK Platform-tools, revision 23.1
- Android SDK Build-tools, revision 23.0.3
- SDK Platform Android 6.0, API 23, revision 3
- Google APIs, Android API 23, revision 1
- Android Support Repository, revision 32
- Android Support Library, revision 23.2.1 (Obsolete)
- Google Play services, revision 30
- Google Repository, revision 26
```

**Comment by jangrewe** [comment]
According to https://dl.google.com/android/repository/addon.xml, revision 23.2.1 is still the current one. I guess it will be updated in short time, then i'll run another build.

**Comment by rzimmer** [comment]
This is because the support libraries are now pulled exclusively from the _Local Maven repository for Support Libraries_, which has been updated _Mon May 16 10:56:32 2016_. In other words, only the local Maven repo will get newer releases than 23.2.1, the sole Android Support Library SDK entry is obsolete and will stick with the old version, see the comment by Ian Lake at this [Google+ annoucement](https://plus.google.com/+AndroidDevelopers/posts/B7QhFkWZ6YX).

**Comment by rzimmer** [comment]
To just give you more feedback: My Gitlab CI build now runs successfully with the release of the new image for my project pulling in version 23.4.0 as Gradle dependency.

Thanks again for your quick action!

**Pull request merged**
