### PR TITLE
Update SDK tools, build tools and sdk version for API 34

### PR DESCRIPTION
**Pull request by cs-nuuk**

### CODE REVIEW

**Comment by michael-winkler** [comment]
@jangrewe Can you merge this please? The current image does not allow builds with target sdk 34 (Android 14)

**Comment by michael-winkler** [comment]
In the meantime I use this for Android 14 and Java 17 support:
https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Android.gitlab-ci.yml


```yaml
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Android.gitlab-ci.yml

# Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
# If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.

image: eclipse-temurin:17-jdk-jammy

variables:

  # ANDROID_COMPILE_SDK is the version of Android you're compiling with.
  # It should match compileSdkVersion.
  ANDROID_COMPILE_SDK: "34"

  # ANDROID_BUILD_TOOLS is the version of the Android build tools you are using.
  # It should match buildToolsVersion.
  ANDROID_BUILD_TOOLS: "34.0.0"

  # It's what version of the command line tools we're going to download from the official site.
  # Official Site-> https://developer.android.com/studio/index.html
  # There, look down below at the cli tools only, sdk tools package is of format:
  #        commandlinetools-os_type-ANDROID_SDK_TOOLS_latest.zip
  # when the script was last modified for latest compileSdkVersion, it was which is written down below
  ANDROID_SDK_TOOLS: "9477386"

# Packages installation before running script
before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget unzip

  # Setup path as android_home for moving/exporting the downloaded sdk into it
  - export ANDROID_HOME="${PWD}/android-sdk-root"
  # Create a new directory at specified location
  - install -d $ANDROID_HOME
  # Here we are installing androidSDK tools from official source,
  # (the key thing here is the url from where you are downloading these sdk tool for command line, so please do note this url pattern there and here as well)
  # after that unzipping those tools and
  # then running a series of SDK manager commands to install necessary android SDK packages that'll allow the app to build
  - wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
  - mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin

  # Nothing fancy here, just checking sdkManager version
  - sdkmanager --version

  # use yes to accept all licenses
  - yes | sdkmanager --licenses > /dev/null || true
  - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager "platform-tools"
  - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"

  # Not necessary, but just for surity
  - chmod +x ./gradlew

# Basic android and gradle stuff
# Check linting
lintDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
  artifacts:
    paths:
      - app/lint/reports/lint-results-debug.html
    expose_as: "lint-report"
    when: always

# Make Project
assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

# Run all tests, if any fails, interrupt the pipeline(fail it)
debugTests:
  needs: [lintDebug, assembleDebug]
  interruptible: true
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
```

**Comment by 10Wyk** [comment]
> In the meantime I use this for Android 14 and Java 17 support: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Android.gitlab-ci.yml
> 
> ```yaml
> # To contribute improvements to CI/CD templates, please follow the Development guide at:
> # https://docs.gitlab.com/ee/development/cicd/templates.html
> # This specific template is located at:
> # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Android.gitlab-ci.yml
> 
> # Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
> # If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.
> 
> image: eclipse-temurin:17-jdk-jammy
> 
> variables:
> 
>   # ANDROID_COMPILE_SDK is the version of Android you're compiling with.
>   # It should match compileSdkVersion.
>   ANDROID_COMPILE_SDK: "34"
> 
>   # ANDROID_BUILD_TOOLS is the version of the Android build tools you are using.
>   # It should match buildToolsVersion.
>   ANDROID_BUILD_TOOLS: "34.0.0"
> 
>   # It's what version of the command line tools we're going to download from the official site.
>   # Official Site-> https://developer.android.com/studio/index.html
>   # There, look down below at the cli tools only, sdk tools package is of format:
>   #        commandlinetools-os_type-ANDROID_SDK_TOOLS_latest.zip
>   # when the script was last modified for latest compileSdkVersion, it was which is written down below
>   ANDROID_SDK_TOOLS: "9477386"
> 
> # Packages installation before running script
> before_script:
>   - apt-get --quiet update --yes
>   - apt-get --quiet install --yes wget unzip
> 
>   # Setup path as android_home for moving/exporting the downloaded sdk into it
>   - export ANDROID_HOME="${PWD}/android-sdk-root"
>   # Create a new directory at specified location
>   - install -d $ANDROID_HOME
>   # Here we are installing androidSDK tools from official source,
>   # (the key thing here is the url from where you are downloading these sdk tool for command line, so please do note this url pattern there and here as well)
>   # after that unzipping those tools and
>   # then running a series of SDK manager commands to install necessary android SDK packages that'll allow the app to build
>   - wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
>   - unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
>   - mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
>   - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin
> 
>   # Nothing fancy here, just checking sdkManager version
>   - sdkmanager --version
> 
>   # use yes to accept all licenses
>   - yes | sdkmanager --licenses > /dev/null || true
>   - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
>   - sdkmanager "platform-tools"
>   - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
> 
>   # Not necessary, but just for surity
>   - chmod +x ./gradlew
> 
> # Basic android and gradle stuff
> # Check linting
> lintDebug:
>   interruptible: true
>   stage: build
>   script:
>     - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
>   artifacts:
>     paths:
>       - app/lint/reports/lint-results-debug.html
>     expose_as: "lint-report"
>     when: always
> 
> # Make Project
> assembleDebug:
>   interruptible: true
>   stage: build
>   script:
>     - ./gradlew assembleDebug
>   artifacts:
>     paths:
>       - app/build/outputs/
> 
> # Run all tests, if any fails, interrupt the pipeline(fail it)
> debugTests:
>   needs: [lintDebug, assembleDebug]
>   interruptible: true
>   stage: test
>   script:
>     - ./gradlew -Pci --console=plain :app:testDebug
> ```

how much time do you spend to build it in gitlab?

**Comment by qwertzui11** [comment]
> In the meantime I use this for Android 14 and Java 17 support: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Android.gitlab-ci.yml

This works surprisingly well for me. Installation time is less than 30s.

**Pull request closed without merging**
